# Project 2

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [2]:
#reading in the data
data = pd.read_csv("abortion_data.csv", encoding='latin1')
data.head()

,U.S. State,"% change in abortion rate, 2017-2020","% change in the no. of abortion clinics, 2017-2020","% change in the no. of abortion providers, 2014-2017","% of all U.S. abortions, by state of occurrence, 2020","% of counties without a known abortion provider, 2014","% of counties without a known clinic, 2020","% of residents obtaining abortions who traveled out of state for care, 2020","% of women aged 15-44 living in a county without a clinic, 2020","% of women aged 15-44 living in a county without an abortion provider, 2014",...,"No. of abortions per 1,000 women aged 15Ð44, by state of occurrence, 2020","No. of abortions per 1,000 women aged 15Ð44, by state of residence, 2020","No. of abortions, by state of occurrence, 2020","No. of abortions, by state of residence, 2020","No. of federally funded abortions, 2010","No. of state funded abortions, 2010","Reported public expenditures for abortions (in 000s of dollars), federal, 2015","Reported public expenditures for abortions (in 000s of dollars), state, 2015","Total no. of publicly funded abortions , 2010","Total reported public expenditures for abortions (in 000s of dollars), 2015"
0,Alabama,-6,0,-22,0.6,91,93,47,59,58,...,6.0,9.5,"5,700","9,060",9,0,22,0,9,22
1,Alaska,0,0,-25,0.1,79,87,7,33,17,...,8.6,9.2,"1,240","1,320",0,835,0,216,835,216
2,Arizona,1,0,-8,1.4,80,80,6,18,19,...,9.3,9.7,"13,320","13,820",1,13,28,11,14,40
3,Arkansas,2,-33,0,0.3,97,99,37,86,77,...,5.6,7.8,"3,250","4,510",0,0,0,0,0,0
4,California,17,7,-18,16.6,24,38,0,3,1,...,19.2,19.0,"154,060","152,400",0,"88,466",0,"32,613","88,466","32,613"

In [3]:
# data.dtypes

In [4]:
#need to do some data cleaning because some of these columns are not of the correct data type
def clean_numbers(num):
    if num == "unavailable":
        num = np.nan
    elif num == "nr": 
        num = np.nan
    elif isinstance(num, str):
        num = num.replace(",", "")
        num = num.strip("<")
        num = num.strip(">")
        num = float(num)
    
    return num

In [5]:
non_num_cols = data.dtypes[data.dtypes == 'object'].index.drop("U.S. State")

In [6]:
for col in non_num_cols: 
    data[col] = data[col].apply(clean_numbers)

data.dtypes

U.S. State                                                                                       object
% change in abortion rate, 2017-2020                                                              int64
% change in the no. of abortion clinics, 2017-2020                                                int64
% change in the no. of abortion providers, 2014-2017                                              int64
% of all U.S. abortions, by state of occurrence, 2020                                           float64
% of counties without a known abortion provider, 2014                                             int64
% of counties without a known clinic, 2020                                                        int64
% of residents obtaining abortions who traveled out of state for care, 2020                       int64
% of women aged 15-44 living in a county without a clinic, 2020                                   int64
% of women aged 15-44 living in a county without an abortion provider, 2014                       int64
Abortion rate (the no. of abortions per 1,000 women aged 15-17), by state of residence, 2017    float64
Abortion rate (the no. of abortions per 1,000 women aged 15-19), by state of residence, 2017    float64
Abortion rate (the no. of abortions per 1,000 women aged 18-19), by state of residence, 2017    float64
Change in the no. of abortion clinics, 2017-2020                                                  int64
Change in the no. of abortion providers, 2014-2017                                                int64
No. of abortion clinics, 2020                                                                     int64
No. of abortion providers, 2017                                                                   int64
No. of abortions among women aged 15-17, by state of residence, 2017                            float64
No. of abortions among women aged 15-19, by state of residence, 2017                            float64
No. of abortions among women aged 18-19, by state of residence, 2017                            float64
No. of abortions among women younger than 15, by state of residence, 2017                       float64
No. of abortions per 1,000 women aged 15Ð44, by state of occurrence, 2020                       float64
No. of abortions per 1,000 women aged 15Ð44, by state of residence, 2020                        float64
No. of abortions, by state of occurrence, 2020                                                  float64
No. of abortions, by state of residence, 2020                                                   float64
No. of federally funded abortions, 2010                                                           int64
No. of state funded abortions, 2010                                                             float64
Reported public expenditures for abortions (in 000s of dollars), federal, 2015                  float64
Reported public expenditures for abortions (in 000s of dollars), state, 2015                    float64
Total no. of publicly funded abortions , 2010                                                   float64
Total reported public expenditures for abortions (in 000s of dollars), 2015                     float64
dtype: object

In [7]:
# px.bar(data, x = "U.S. State", y = '% of all U.S. abortions, by state of occurrence, 2020')

In [8]:
# px.bar(data, x = "U.S. State", y = '% change in abortion rate, 2017-2020')

In [9]:
#misleading visualization: focus only on the states where the abortion rate decreased --> use it for pro life

#filtering the data so that it's only the states where the abortion rate increased
# just_inc = data[["U.S. State", '% change in abortion rate, 2017-2020']]
# just_inc = just_inc[just_inc["% change in abortion rate, 2017-2020"] > 0 ]

In [10]:
# px.bar(just_inc, x = "U.S. State", y = '% change in abortion rate, 2017-2020')

In [11]:
# data.dtypes

In [12]:
# px.scatter(data, x = "No. of abortions among women aged 15-17, by state of residence, 2017", 
#            y = 'No. of federally funded abortions, 2010', color = "U.S. State" )

In [13]:
print(data.columns)

Index(['U.S. State', '% change in abortion rate, 2017-2020',
       '% change in the no. of abortion clinics, 2017-2020',
       '% change in the no. of abortion providers, 2014-2017',
       '% of all U.S. abortions, by state of occurrence, 2020',
       '% of counties without a known abortion provider, 2014',
       '% of counties without a known clinic, 2020',
       '% of residents obtaining abortions who traveled out of state for care, 2020',
       '% of women aged 15-44 living in a county without a clinic, 2020',
       '% of women aged 15-44 living in a county without an abortion provider, 2014',
       'Abortion rate (the no. of abortions per 1,000 women aged 15-17), by state of residence, 2017',
       'Abortion rate (the no. of abortions per 1,000 women aged 15-19), by state of residence, 2017',
       'Abortion rate (the no. of abortions per 1,000 women aged 18-19), by state of residence, 2017',
       'Change in the no. of abortion clinics, 2017-2020',
       'Change in the no. of abortion providers, 2014-2017',
       'No. of abortion clinics, 2020', 'No. of abortion providers, 2017',
       'No. of abortions among women aged 15-17, by state of residence, 2017',
       'No. of abortions among women aged 15-19, by state of residence, 2017',
       'No. of abortions among women aged 18-19, by state of residence, 2017',
       'No. of abortions among women younger than 15, by state of residence, 2017',
       'No. of abortions per 1,000 women aged 15Ð44, by state of occurrence, 2020',
       'No. of abortions per 1,000 women aged 15Ð44, by state of residence, 2020',
       'No. of abortions, by state of occurrence, 2020',
       'No. of abortions, by state of residence, 2020',
       'No. of federally funded abortions, 2010',
       'No. of state funded abortions, 2010',
       'Reported public expenditures for abortions (in 000s of dollars), federal, 2015',
       'Reported public expenditures for abortions (in 000s of dollars), state, 2015',
       'Total no. of publicly funded abortions , 2010',
       'Total reported public expenditures for abortions (in 000s of dollars), 2015'],
      dtype='object')

In [14]:
sex_ed_grades = {
    "Alabama": "C", 
    "Alaska": "D", 
    "Arizona": "F", 
    "Arkansas": "F",
    "California": "B", 
    "Colorado": "B", 
    "Connecticut": "D", 
    "Delaware": "C", 
    "District of Columbia": "B",
    "Florida": "F",
    "Georgia": "D",
    "Hawaii": "C",
    "Idaho": "D", 
    "Illinois": "A",
    "Indiana": "F",
    "Iowa": "C", 
    "Kansas": "D", 
    "Kentucky": "F",
    "Louisiana": "D", 
    "Maine": "B",
    "Maryland": "B", 
    "Massachusetts": "D",
    "Michigan": "D",
    "Minnesota": "D",
    "Mississippi":"F",
    "Missouri": "C",
    "Montana": "C",
    "Nebraska": "F",
    "Nevada": "C",
    "New Hampshire": "C",
    "New Jersey": "B",
    "New Mexico": "C",
    "New York": "D",
    "North Carolina": "C",
    "North Dakota": "D",
    "Ohio": "D",
    "Oklahoma": "D", 
    "Oregon": "A",
    "Pennsylvania": "D",
    "Rhode Island": "B",
    "South Carolina": "C",
    "Tennessee": "C",
    "Texas": "B",
    "Utah": "B",
    "Vermont": "D",
    "Washington": "D",
    "West Virgina": "F",
    "Wisconsin": "C",
    "Wyoming": "C"
}

In [15]:
# sex_ed_added = data.copy()
# sex_ed_added = sex_ed_added.set_index("U.S. State")
# sex_ed_added["Sex Ed Score"] = pd.Series(sex_ed_grades)
# sex_ed_added.head()

In [16]:
# px.bar(sex_ed_added.reset_index(), 
#        x = "U.S. State",
#          y = "No. of abortions among women aged 15-17, by state of residence, 2017",
#          color = "Sex Ed Score")

In [17]:
# px.choropleth(data, locations='U.S. State',
#               locationmode="USA-states",
#                 color = '% of counties without a known clinic, 2020',
#               scope = "usa")

In [18]:
us_states = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
    'District of Columbia': 'DC'
}

In [19]:
add_code = data.copy().set_index("U.S. State")
add_code["abbr"] = us_states
add_code = add_code.reset_index()

In [20]:
# px.choropleth(add_code, locations='abbr',
#               locationmode="USA-states",
#                 color = '% of counties without a known clinic, 2020',
#               scope = "usa")

In [21]:
# # want to bin the percent of counties without clinic
# def cat_percent(perc):
#     if perc < 20:
#         return "<20%"
#     elif perc <= 40: 
#         return "20-40%"
#     elif perc <= 60: 
#         return "40-60%"
#     elif perc <= 80: 
#         return "60-80%"
#     elif perc <= 100: 
#         return ">80%"

In [22]:
# add_code["binned_percent_counties_wo"] = add_code["% of counties without a known clinic, 2020"].apply(cat_percent)

In [23]:
# fig1 = px.choropleth(add_code, locations='abbr',
#               locationmode="USA-states",
#                 color = 'binned_percent_counties_wo',
#               scope = "usa",
#               category_orders= {"binned_percent_counties_wo": ["<20%", "20-40%", "40-60%", "60-80%", ">80%"]}
#               )
# fig1.update_layout(
#     legend = dict(title = "Percent of Counties <br>Without An Abortion Clinic")
# )

In [24]:
# px.bar(add_code, x = "U.S. State", y = "Abortion rate (the no. of abortions per 1,000 women aged 15-17), by state of residence, 2017")

In [25]:
# from plotly.subplots import make_subplots
# fig = make_subplots(specs=[[{"secondary_y": True}]])

# # Add bar trace (left y-axis)
# fig.add_trace(
#     go.Bar(x=add_code["U.S. State"], y=add_code["Abortion rate (the no. of abortions per 1,000 women aged 15-17), by state of residence, 2017"], name="Bar Data", marker_color='skyblue'),
#     secondary_y=False,
# )

# # Add line trace (right y-axis)
# fig.add_trace(
#     go.Scatter(x=add_code["U.S. State"], y=add_code["Total reported public expenditures for abortions (in 000s of dollars), 2015"], name="Line Data", mode='lines+markers', line=dict(color='red')),
#     secondary_y=True,
# )

# # Set axis titles
# fig.update_layout(
#     title_text="Bar + Line Plot with Dual Y-Axes",
#     xaxis_title="Month",
# )

# fig.update_yaxes(title_text="Bar Values", secondary_y=False)
# fig.update_yaxes(title_text="Line Values", secondary_y=True)

# # Show figure
# fig.show()

In [26]:
# fig2 = px.choropleth(add_code, locations='abbr',
#               locationmode="USA-states",
#                 color = "Abortion rate (the no. of abortions per 1,000 women aged 15-17), by state of residence, 2017",
#               scope = "usa", color_continuous_scale= ["red", "yellow"]
#             #   category_orders= {"binned_percent_counties_wo": ["<20%", "20-40%", "40-60%", "60-80%", ">80%"]}
#               )
# fig2.show()

In [27]:
def bin_abortion_rate(rate): 
    if rate < 0: 
        return "-2-0%"
    elif rate < 2:
        return "0-2%"
    elif rate <= 4: 
        return "2-4%"
    elif rate <= 6: 
        return "4-6%"
    elif rate <= 8:
        return "6-8%"
    elif rate <= 10: 
        return "8-10%"
    elif rate <= 12: 
        return "10-12%"
    elif rate <= 14:
        return "12-14%"
    else: 
        return ">14%"

In [28]:
add_code["bin_ab_R"] = add_code["Abortion rate (the no. of abortions per 1,000 women aged 15-17), by state of residence, 2017"].apply(bin_abortion_rate)

In [29]:
#PRO LIFE: teen abortion rate, identfy states where the rate is hghe or lower than the mean
# fig3 = px.choropleth(add_code, locations='abbr',
#               locationmode="USA-states",
#                 color = "bin_ab_R",
#               scope = "usa"
#             #   category_orders= {"binned_percent_counties_wo": ["<20%", "20-40%", "40-60%", "60-80%", ">80%"]}
#               )
# fig3.show()

In [30]:
# fig4 = px.choropleth(add_code, locations='abbr',
#               locationmode="USA-states",
#                 color = "% of all U.S. abortions, by state of occurrence, 2020",
#               scope = "usa", 
#               # color_continuous_scale= ["red", "yellow", "blue"]
#             #   category_orders= {"binned_percent_counties_wo": ["<20%", "20-40%", "40-60%", "60-80%", ">80%"]}
#               )
# fig4.show()

In [31]:
#another idea: do difference in mean %

mean_abr_rate = add_code["% of all U.S. abortions, by state of occurrence, 2020"].mean()

In [32]:
diff_from_mean = add_code["% of all U.S. abortions, by state of occurrence, 2020"] - mean_abr_rate
diff_from_mean

0     -1.352941
1     -1.852941
2     -0.552941
3     -1.652941
4     14.647059
5     -0.552941
6     -0.752941
7     -1.752941
8     -0.952941
9      6.347059
10     2.547059
11    -1.652941
12    -1.752941
13     3.747059
14    -1.152941
15    -1.552941
16    -1.052941
17    -1.552941
18    -1.152941
19    -1.652941
20     1.347059
21    -0.152941
22     1.447059
23    -0.752941
24    -1.552941
25    -1.952941
26    -1.752941
27    -1.752941
28    -0.752941
29    -1.752941
30     3.247059
31    -1.352941
32     9.947059
33     1.447059
34    -1.852941
35     0.347059
36    -0.952941
37    -1.052941
38     1.547059
39    -1.652941
40    -1.352941
41    -1.952941
42    -0.752941
43     4.247059
44    -1.652941
45    -1.852941
46     0.047059
47    -0.052941
48    -1.852941
49    -1.252941
50    -1.952941
Name: % of all U.S. abortions, by state of occurrence, 2020, dtype: float64

In [33]:
y = diff_from_mean.apply(bin_abortion_rate)
add_code["y"] = y
fig5 = px.choropleth(add_code, locations='abbr',
              locationmode="USA-states",
                color = "y",
              scope = "usa", 
              # color_continuous_scale= ["red", "yellow", "blue"]
              category_orders= {"y": ["-2-0%",
                                    "0-2%", 
                                    "2-4%",
                                    "4-6%",
                                    "6-8%",
                                    "8-10%",
                                    "10-12%",
                                    "12-14%",
                                    ">14%"]},
                                    title = "California Performs Abortions at Highest Rate of All States"
              )
fig5.update_layout(legend = dict(title = "Percent Difference in Rate<br>of Total Abortions Performed Per State<br>Relative to National Mean"))
fig5.show()

#PRO LIFE: show that california is performing disproportionate amount of abortions

In [34]:
# #PRO CHOICE: abortion access needs to be expanded
# access_df = add_code[['abbr', '% of residents obtaining abortions who traveled out of state for care, 2020']]
# access_df['cat_percent_travel'] = access_df['% of residents obtaining abortions who traveled out of state for care, 2020'].apply(
#     cat_percent
# )

# fig6 = px.choropleth(access_df, locations='abbr',
#               locationmode="USA-states",
#                 color = "cat_percent_travel",
#               scope = "usa", 
#               # color_continuous_scale= ["red", "yellow", "blue"]
#               category_orders= {"cat_percent_travel": ["<20%", "20-40%", "40-60%", "60-80%", ">80%"]},
#               title = "In Some States, A Sizable Amount of Women Must Travel For Abortion Care"
#               )
# fig6.update_layout(legend = dict(title = "Percent of Residents Obtaining Abortions<br> Travelling Out of State for Care, 2020"))
# fig6.show()

In [35]:
# #count plot for binned % of counties without abortion providers

# count_df = add_code.groupby("binned_percent_counties_wo")[["U.S. State"]].count().reset_index()
# px.bar(count_df, 
#        x = "binned_percent_counties_wo",
#          y = "U.S. State",
#          category_orders= {"binned_percent_counties_wo": ["<20%", "20-40%", "40-60%", "60-80%", ">80%"]}, 
#          labels = {
#              "U.S. State": "Number of U.S. States", "binned_percent_counties_wo": "Percent of Counties Without Abortion Clinics"
#          }, title = "The Majority of U.S. States Have More than 80% of Counties without Abortion Clinics")

In [36]:
# px.scatter(data,
#            x = "% change in the no. of abortion clinics, 2017-2020",
#            y = 'No. of abortions per 1,000 women aged 15Ð44, by state of occurrence, 2020',
#            labels={
#              "No. of abortions per 1,000 women aged 15Ð44, by state of occurrence, 2020": "Abortion Rate (per 1000 women aged 15-44), 2020",
#              "% change in the no. of abortion clinics, 2017-2020": "Percent Change in Number of Abortion Clinics, 2017-2020"
#            }, title = "States with A 20% increase or decrease in <br>number of abortion clinics saw no significant change in number of abortions")

In [37]:
add_code.head()

,U.S. State,"% change in abortion rate, 2017-2020","% change in the no. of abortion clinics, 2017-2020","% change in the no. of abortion providers, 2014-2017","% of all U.S. abortions, by state of occurrence, 2020","% of counties without a known abortion provider, 2014","% of counties without a known clinic, 2020","% of residents obtaining abortions who traveled out of state for care, 2020","% of women aged 15-44 living in a county without a clinic, 2020","% of women aged 15-44 living in a county without an abortion provider, 2014",...,"No. of abortions, by state of residence, 2020","No. of federally funded abortions, 2010","No. of state funded abortions, 2010","Reported public expenditures for abortions (in 000s of dollars), federal, 2015","Reported public expenditures for abortions (in 000s of dollars), state, 2015","Total no. of publicly funded abortions , 2010","Total reported public expenditures for abortions (in 000s of dollars), 2015",abbr,bin_ab_R,y
0,Alabama,-6,0,-22,0.6,91,93,47,59,58,...,9060.0,9,0.0,22.0,0.0,9.0,22.0,AL,2-4%,-2-0%
1,Alaska,0,0,-25,0.1,79,87,7,33,17,...,1320.0,0,835.0,0.0,216.0,835.0,216.0,AK,2-4%,-2-0%
2,Arizona,1,0,-8,1.4,80,80,6,18,19,...,13820.0,1,13.0,28.0,11.0,14.0,40.0,AZ,2-4%,-2-0%
3,Arkansas,2,-33,0,0.3,97,99,37,86,77,...,4510.0,0,0.0,0.0,0.0,0.0,0.0,AR,0-2%,-2-0%
4,California,17,7,-18,16.6,24,38,0,3,1,...,152400.0,0,88466.0,0.0,32613.0,88466.0,32613.0,CA,4-6%,>14%

In [38]:
#writing a new aggregation function
def pnp(grade):
    if grade in ["A", "B", "C"]:
        return "Pass"
    else:
        return "Fail"

In [39]:


sex_ed_added = add_code.copy()
sex_ed_added = sex_ed_added.set_index("U.S. State")
sex_ed_added["Sex Ed Score"] = pd.Series(sex_ed_grades)
sex_ed_added.head()

,"% change in abortion rate, 2017-2020","% change in the no. of abortion clinics, 2017-2020","% change in the no. of abortion providers, 2014-2017","% of all U.S. abortions, by state of occurrence, 2020","% of counties without a known abortion provider, 2014","% of counties without a known clinic, 2020","% of residents obtaining abortions who traveled out of state for care, 2020","% of women aged 15-44 living in a county without a clinic, 2020","% of women aged 15-44 living in a county without an abortion provider, 2014","Abortion rate (the no. of abortions per 1,000 women aged 15-17), by state of residence, 2017",...,"No. of federally funded abortions, 2010","No. of state funded abortions, 2010","Reported public expenditures for abortions (in 000s of dollars), federal, 2015","Reported public expenditures for abortions (in 000s of dollars), state, 2015","Total no. of publicly funded abortions , 2010","Total reported public expenditures for abortions (in 000s of dollars), 2015",abbr,bin_ab_R,y,Sex Ed Score
U.S. State,,,,,,,,,,,,,,,,,,,,,
Alabama,-6,0,-22,0.6,91,93,47,59,58,2.4,...,9,0.0,22.0,0.0,9.0,22.0,AL,2-4%,-2-0%,C
Alaska,0,0,-25,0.1,79,87,7,33,17,3.6,...,0,835.0,0.0,216.0,835.0,216.0,AK,2-4%,-2-0%,D
Arizona,1,0,-8,1.4,80,80,6,18,19,2.1,...,1,13.0,28.0,11.0,14.0,40.0,AZ,2-4%,-2-0%,F
Arkansas,2,-33,0,0.3,97,99,37,86,77,1.7,...,0,0.0,0.0,0.0,0.0,0.0,AR,0-2%,-2-0%,F
California,17,7,-18,16.6,24,38,0,3,1,4.7,...,0,88466.0,0.0,32613.0,88466.0,32613.0,CA,4-6%,>14%,B

In [40]:
sex_ed_added["pass"] = sex_ed_added["Sex Ed Score"].apply(pnp)
sex_ed_added.columns

Index(['% change in abortion rate, 2017-2020',
       '% change in the no. of abortion clinics, 2017-2020',
       '% change in the no. of abortion providers, 2014-2017',
       '% of all U.S. abortions, by state of occurrence, 2020',
       '% of counties without a known abortion provider, 2014',
       '% of counties without a known clinic, 2020',
       '% of residents obtaining abortions who traveled out of state for care, 2020',
       '% of women aged 15-44 living in a county without a clinic, 2020',
       '% of women aged 15-44 living in a county without an abortion provider, 2014',
       'Abortion rate (the no. of abortions per 1,000 women aged 15-17), by state of residence, 2017',
       'Abortion rate (the no. of abortions per 1,000 women aged 15-19), by state of residence, 2017',
       'Abortion rate (the no. of abortions per 1,000 women aged 18-19), by state of residence, 2017',
       'Change in the no. of abortion clinics, 2017-2020',
       'Change in the no. of abortion providers, 2014-2017',
       'No. of abortion clinics, 2020', 'No. of abortion providers, 2017',
       'No. of abortions among women aged 15-17, by state of residence, 2017',
       'No. of abortions among women aged 15-19, by state of residence, 2017',
       'No. of abortions among women aged 18-19, by state of residence, 2017',
       'No. of abortions among women younger than 15, by state of residence, 2017',
       'No. of abortions per 1,000 women aged 15Ð44, by state of occurrence, 2020',
       'No. of abortions per 1,000 women aged 15Ð44, by state of residence, 2020',
       'No. of abortions, by state of occurrence, 2020',
       'No. of abortions, by state of residence, 2020',
       'No. of federally funded abortions, 2010',
       'No. of state funded abortions, 2010',
       'Reported public expenditures for abortions (in 000s of dollars), federal, 2015',
       'Reported public expenditures for abortions (in 000s of dollars), state, 2015',
       'Total no. of publicly funded abortions , 2010',
       'Total reported public expenditures for abortions (in 000s of dollars), 2015',
       'abbr', 'bin_ab_R', 'y', 'Sex Ed Score', 'pass'],
      dtype='object')

In [41]:
#grouping by the passes and the non passes
mean_df = sex_ed_added.drop(columns = ['abbr', 'bin_ab_R', 'y', 'Sex Ed Score','Sex Ed Score']).groupby("pass").mean()

#change in abortion rate decreased in passing states and increased in failing states
#mwan aboirtion rate in 2017 is greater in passing states than failing states 
mean_df[['Abortion rate (the no. of abortions per 1,000 women aged 15-17), by state of residence, 2017',
       'Abortion rate (the no. of abortions per 1,000 women aged 15-19), by state of residence, 2017',
       'Abortion rate (the no. of abortions per 1,000 women aged 18-19), by state of residence, 2017',
       'Change in the no. of abortion clinics, 2017-2020',
       'Change in the no. of abortion providers, 2014-2017',
       'No. of abortion clinics, 2020', 'No. of abortion providers, 2017',
       'No. of abortions among women aged 15-17, by state of residence, 2017',
       'No. of abortions among women aged 15-19, by state of residence, 2017',
       'No. of abortions among women aged 18-19, by state of residence, 2017',
         'No. of abortions among women younger than 15, by state of residence, 2017']]

,"Abortion rate (the no. of abortions per 1,000 women aged 15-17), by state of residence, 2017","Abortion rate (the no. of abortions per 1,000 women aged 15-19), by state of residence, 2017","Abortion rate (the no. of abortions per 1,000 women aged 18-19), by state of residence, 2017","Change in the no. of abortion clinics, 2017-2020","Change in the no. of abortion providers, 2014-2017","No. of abortion clinics, 2020","No. of abortion providers, 2017","No. of abortions among women aged 15-17, by state of residence, 2017","No. of abortions among women aged 15-19, by state of residence, 2017","No. of abortions among women aged 18-19, by state of residence, 2017","No. of abortions among women younger than 15, by state of residence, 2017"
pass,,,,,,,,,,,
Fail,3.066667,5.857692,10.577778,-0.846154,0.961538,14.576923,27.807692,465.555556,1453.846154,1112.222222,63.526316
Pass,3.744444,7.436000,11.766667,0.680000,-4.360000,17.120000,34.560000,515.555556,1584.800000,1255.555556,53.333333

In [42]:
sum_df = sex_ed_added.drop(columns = ['abbr', 'bin_ab_R', 'y', 'Sex Ed Score']).groupby("pass").sum()

sum_df[['Abortion rate (the no. of abortions per 1,000 women aged 15-17), by state of residence, 2017',
       'Abortion rate (the no. of abortions per 1,000 women aged 15-19), by state of residence, 2017',
       'Abortion rate (the no. of abortions per 1,000 women aged 18-19), by state of residence, 2017',
       'Change in the no. of abortion clinics, 2017-2020',
       'Change in the no. of abortion providers, 2014-2017',
       'No. of abortion clinics, 2020', 'No. of abortion providers, 2017',
       'No. of abortions among women aged 15-17, by state of residence, 2017',
       'No. of abortions among women aged 15-19, by state of residence, 2017',
       'No. of abortions among women aged 18-19, by state of residence, 2017',
       'No. of abortions among women younger than 15, by state of residence, 2017']]

,"Abortion rate (the no. of abortions per 1,000 women aged 15-17), by state of residence, 2017","Abortion rate (the no. of abortions per 1,000 women aged 15-19), by state of residence, 2017","Abortion rate (the no. of abortions per 1,000 women aged 18-19), by state of residence, 2017","Change in the no. of abortion clinics, 2017-2020","Change in the no. of abortion providers, 2014-2017","No. of abortion clinics, 2020","No. of abortion providers, 2017","No. of abortions among women aged 15-17, by state of residence, 2017","No. of abortions among women aged 15-19, by state of residence, 2017","No. of abortions among women aged 18-19, by state of residence, 2017","No. of abortions among women younger than 15, by state of residence, 2017"
pass,,,,,,,,,,,
Fail,55.2,152.3,190.4,-22,25,379,723,8380.0,37800.0,20020.0,1207.0
Pass,67.4,185.9,211.8,17,-109,428,864,9280.0,39620.0,22600.0,960.0

In [43]:
#WE ARE COOKING
#my two visualizations: 
#mean df: abortion rate 15-19yo is lower in states with a failing grades
#sum df: number of total aboirtions given to women younger than 15 is greater in states with failing grades comapred to passing grades

#FUCK UP THIS Y AXIS YES
#bar charts for the fucking win

In [53]:
fig_map = {"Pass":"red", "Fail": "blue" }

fig = px.bar(mean_df,
    x = mean_df.index,
    y="Abortion rate (the no. of abortions per 1,000 women aged 15-19), by state of residence, 2017",
    range_y=[4.5, mean_df["Abortion rate (the no. of abortions per 1,000 women aged 15-19), by state of residence, 2017"].max()], 
    color = mean_df.index, color_discrete_map=fig_map,
    title =  "More Sex Ed, More Teen Abortions?", subtitle= "States with Stronger Sex Ed Programs Report Higher Abortion Rates Among Teens"
    )

fig.update_layout(xaxis_title = "Sex Education Score",
                   yaxis_title = "Mean Abortion Rate<br>(Number of Abortions per 1,000 women)<br>in 15-19 year olds, 2017",
                   showlegend = False,
                   plot_bgcolor="white")
fig.show()

In [55]:
fig2_map = {"Pass": "blue", "Fail": "red"}
fig2 = px.bar(sum_df,
              x = sum_df.index,
       y = "No. of abortions among women younger than 15, by state of residence, 2017",
       range_y = [900,sum_df["No. of abortions among women younger than 15, by state of residence, 2017"].max()],
       color = sum_df.index, color_discrete_map=fig2_map, 
       title = "Where Sex Ed Doesn't Work, More Girls Need Abortions",
       subtitle= "Inadequate Programs Linked to More Abortions In The Youngest Teens")

fig2.update_layout(xaxis_title = "Sex Education Score",
                   yaxis_title = "Total Number of Abortions in Women Under 15, 2017",
                   showlegend = False,
                   plot_bgcolor="white")

fig2.show()